package com.vulnweave;

import java.net.*;
import java.net.http.*;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.*;

final class VeracodeClient {
    private final SettingsStore settings; private final HttpClient http=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(15)).build();
    VeracodeClient(SettingsStore s){settings=s;}
    private String host(){String r=settings.get("veracode.region");return "eu".equals(r)?"api.veracode.eu":"us".equals(r)?"api.veracode.us":"api.veracode.com";}
    private String token()throws Exception{String id=settings.getSecret("veracode.clientId"),secret=settings.getSecret("veracode.clientSecret");if(id==null||secret==null)throw new IllegalStateException("Veracode OAuth not configured");String basic=Base64.getEncoder().encodeToString((id+":"+secret).getBytes(StandardCharsets.UTF_8));HttpRequest req=HttpRequest.newBuilder(URI.create("https://"+host()+"/api/authn/v2/oauth2/token")).timeout(Duration.ofSeconds(30)).header("Authorization","Basic "+basic).header("Content-Type","application/x-www-form-urlencoded").header("Accept","application/json").POST(HttpRequest.BodyPublishers.ofString("grant_type=client_credentials")).build();HttpResponse<String>res=http.send(req,HttpResponse.BodyHandlers.ofString());if(res.statusCode()/100!=2)throw new IllegalStateException("Veracode OAuth HTTP "+res.statusCode());Map<String,Object>j=MiniJson.map(MiniJson.parse(res.body()));String t=MiniJson.str(j,"access_token");if(t.isBlank())throw new IllegalStateException("Veracode OAuth did not return access_token");return t;}
    Map<String,Object> correlate(Map<String,Object> risk)throws Exception{String guid=settings.get("veracode.appGuid");if(guid.isBlank())throw new IllegalStateException("Configure Veracode application GUID first");String t=token();String url="https://"+host()+"/appsec/v2/applications/"+URLEncoder.encode(guid,StandardCharsets.UTF_8)+"/findings?scan_type=SCA&size=500";HttpRequest req=HttpRequest.newBuilder(URI.create(url)).timeout(Duration.ofSeconds(60)).header("Authorization","Bearer "+t).header("Accept","application/json").header("Content-Type","application/json").header("User-Agent","VulnWeave/0.12.4").GET().build();HttpResponse<String>res=http.send(req,HttpResponse.BodyHandlers.ofString());if(res.statusCode()/100!=2)throw new IllegalStateException("Veracode Findings HTTP "+res.statusCode()+": "+res.body().substring(0,Math.min(400,res.body().length())));Map<String,Object>root=MiniJson.map(MiniJson.parse(res.body()));Object embedded=root.get("_embedded");List<Object> findings=embedded instanceof Map?MiniJson.list(MiniJson.map(embedded).get("findings")):MiniJson.list(root.get("findings"));Set<String>cves=new HashSet<>();for(Object a0:MiniJson.list(risk.get("advisories"))){Map<String,Object>a=MiniJson.map(a0);String id=MiniJson.str(a,"id");if(id.startsWith("CVE-"))cves.add(id);for(Object alias:MiniJson.list(a.get("aliases"))){String x=String.valueOf(alias);if(x.startsWith("CVE-"))cves.add(x);}}
        List<Object>matches=new ArrayList<>();for(Object f0:findings){Map<String,Object>f=MiniJson.map(f0);Map<String,Object>d=f.get("finding_details") instanceof Map?MiniJson.map(f.get("finding_details")):Map.of();Map<String,Object>cve=d.get("cve") instanceof Map?MiniJson.map(d.get("cve")):Map.of();String cveName=MiniJson.str(cve,"name");if(!cveName.isBlank()&&cves.contains(cveName)){Map<String,Object>m=new LinkedHashMap<>();m.put("cve",cveName);m.put("component",d.get("component_filename"));m.put("version",d.get("version"));m.put("violatesPolicy",f.get("violates_policy"));Map<String,Object>st=f.get("finding_status") instanceof Map?MiniJson.map(f.get("finding_status")):Map.of();m.put("status",st.get("status"));m.put("resolution",st.get("resolution"));matches.add(m);}}
        return new LinkedHashMap<>(Map.of("application",settings.get("veracode.appName").isBlank()?guid:settings.get("veracode.appName"),"mode","read-only","totalSCAFindings",findings.size(),"matches",matches));
    }
}
